// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3BUheHIsEL1jvigK6jP7r4YJ0fzS6g80',
    appId: '1:537815017333:web:37784db9cec805df0c153c',
    messagingSenderId: '537815017333',
    projectId: 'okventa-403e4',
    authDomain: 'okventa-403e4.firebaseapp.com',
    storageBucket: 'okventa-403e4.firebasestorage.app',
    measurementId: 'G-01Q59940G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI14JKDX5UXnlrL095EzurbgdO4M1eQmw',
    appId: '1:537815017333:android:03d4beed71bdd1a70c153c',
    messagingSenderId: '537815017333',
    projectId: 'okventa-403e4',
    storageBucket: 'okventa-403e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiP_-0j3ZIBfWHt20KFC-j8kpnGY_jKOo',
    appId: '1:537815017333:ios:515a440ba028e6720c153c',
    messagingSenderId: '537815017333',
    projectId: 'okventa-403e4',
    storageBucket: 'okventa-403e4.firebasestorage.app',
    iosBundleId: 'com.fepinto.mercadofoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiP_-0j3ZIBfWHt20KFC-j8kpnGY_jKOo',
    appId: '1:537815017333:ios:34755cdfb197bf650c153c',
    messagingSenderId: '537815017333',
    projectId: 'okventa-403e4',
    storageBucket: 'okventa-403e4.firebasestorage.app',
    iosBundleId: 'com.example.mercadofotoApp',
  );
}
